a = input('Digite algo: ')
print('O tipo primitivo desse valor é: ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numero? ', a.isalnum())
print('É alfabetico? ', a.isalpha())
print('teste: ', a.isupper())
